# This workflow will do a clean install of node dependencies, 
# build the source code and run tests across different versions of node
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NovaScriptelper CI

on:
  push:
    branches:
      - 'staging'
  pull_request:
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: npm i
    - run: node run server.js
